name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp_version: [26, 27, 28]
    steps:
    - name: CHECKOUT
      uses: actions/checkout@v2
    - name: CONFIGURE ERLANG
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_version }}
    - name: XREF
      run: make xref
    - name: DEPS
      run: make test-deps
    - name: DIALYZE
      if: ${{ matrix.otp_version == 27}}
      run: make dialyze
    - name: BUILD
      run: make test-build
    - name: EUNIT
      run: make eunit
    - name: COMMON TEST
      run: make ct
    - name: PROPER
      run: make proper
    - name: CAPTURE TEST LOGS ON FAILURE
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: ct-logs-${{matrix.otp_version}}
        path: logs/*
